db.products.insertMany([
    {  
        name:"Alan",
        email:"alan@email.com",
        pass:1234,
    },
    {   
        name:"Dan",
        email:"dan@email.com",
        pass:1234,
    },
]);